### PR TITLE
added netlify banner to qualify for free hosting

### PR DESCRIPTION
**Pull request by cholmes**
This could likely be nicer, but just want to get something working.

### CODE REVIEW

**Comment by m-mohr** [comment]
As far as I understood, the link must be present on the hosted pages itself, not on the link list. This page is hosted on GH, so I think we don't need this PR. 🤔

**Comment by cholmes** [comment]
Hrm, that will be more difficult. The email with the netlify people said: 'We require a link to our service on your project's main web page for your website's visitors to see (so, not just in your repository documentation or on a sponsors page).' I think that'd be a stac-browser webpage if we had one, I think stacspec.org may be the best option. We could put it in and see what they say.

**Comment by m-mohr** [comment]
I understood that as the main website that's hosted by netlify, but maybe we should clarify that with them.

**Comment by cholmes** [comment]
I'm going to merge in so we can show them this version. If this isn't good enough I'll revert it.

**Pull request merged**
