### PR TITLE
Updating STAC Tutorials

### PR DESCRIPTION
**Pull request by PowerChell**
### Updates made in this PR:

1. Updated the Introduction to STAC tutorial. 
- This tutorial is a combination of the content from the two existing pages on the stac-site: About STAC: [The STAC Specification](https://stacspec.org/en/about/stac-spec/) and [Tutorials: Intro to STAC: an Overview of the Specification](https://stacspec.org/en/tutorials/intro-to-stac/).
- Updated existing figures and added needed figures. 
- Slimmed down content to focus only on the components that are needed to understand the basics of STAC. I propose we move the following removed sections into their own page/document: 
   - STAC Catalog Relation and Media Types (would better fit  in an FAQ style section)
   - Dynamic vs Static STAC Catalogs (also would better fit  in an FAQ style section)
   - STAC API (perhaps this should have its own intro tutorial instead of being tossed in at the bottom of this one like it was before)
2. Added basic Python STAC tutorials 
- tutorials modified from the [PySTAC site](https://pystac.readthedocs.io/en/stable/).
3. Added basic STAC API Browser QGIS Plugin tutorials 
 - tutorials adapted from the learning material on the [QGIS STAC API Browser Documentation Site](https://stac-utils.github.io/qgis-stac-plugin/).
4. Updated the homepage to display the new tutorial sections. 
5. Renamed the current "Notebooks" section to "How-to Guides" to align more with the [Divio Documentation System](https://documentation.divio.com/introduction/#) description of [How-to Guides](https://documentation.divio.com/how-to-guides/) for the STAC Specification: the How-to Guide section provides "answer(s) to a question that only a user with some experience could even formulate."

### Remaining doubts/questions from me:
1. Is there a reason the tutorial display is so narrow? If there is not a good reason, I think we should widen it so that the content fills the space better.
2. Google Colab/Binder is not working locally, but based on the error message it looks like its trying to fetch it from the api response of the notebooks that are on the site (see `https://api.github.com/repos/radiantearth/stac-site/contents/notebooks/src` response). I believe these should work once the notebooks are incorporated into main, but we will need to check this to make sure. 
3. I put the `example-catalog` in the `_site/public directory` since that is where I was able to store and access embedded images, but I am not sure this is how we want to display this notebook to the user. In the development of these notebooks, the file was stored in the same directory as the Jupyter Notebooks, but with the html rendering of the notebooks, that file format does not work. I am open to different storage opens for the `example-catalog` (Used in the first Python tutorial).

### CODE REVIEW

**Review by cholmes — APPROVED** [review]
Looks great! I put in a lot of suggestions on the QGIS one, since I think that'll be a first landing point for many people and it should be a simple way to show people the power of STAC, without giving them too much to think about. I think there's a clear follow-on 'how to' which would be 'how to use qgis to search any stac catalog', with tips on how to do that well (check conformance, etc). The other 'data user' tutorial that could be good to have is 'how to use stac index to find data', and just show how you can use the included stac browser to check out what's available.

The python one I only reviewed quickly, as I've got a lot I need to get done today, but it generally looked good. The only thing I'd say is that it could add a bit more of the 'why' - help people see the reason for doing what you take them through. It could also use some more 'what's next' I think.

The one other thing I'd really like to see is a clear link from the 'get involved' pages (data users to qgis, developers to python). Like I think 'do the tutorial' should be the clear 'call to action' - when you read one of those pages and decide, 'yes, I'd like to learn more', let's point people directly to a tutorial. And then at the end of the tutorial we should guide them to what to do next. Like really think about a new user coming in and how we teach them about STAC. I think the tutorials are great - give people a concrete win and experience of using STAC. 

We should figure out what the 'data provider' tutorial is, but there's also not a super clear answer yet. But when radiant earth has a clear product where you just upload you're data then that to me would be the ideal one. Indeed it could make sense to have like a 'sandbox' where people can easily upload and see how it works, see how they get stac browser, etc.

**Comment by cholmes** [comment]
> Is there a reason the tutorial display is so narrow? If there is not a good reason, I think we should widen it so that the content fills the space better.

No idea. @stuartpearman - any insight? Or objection to widening? I'm not opposed at all - feel free to just go for it if we don't hear from Stuart.

> Google Colab/Binder is not working locally, but based on the error message it looks like its trying to fetch it from the api response of the notebooks that are on the site (see https://api.github.com/repos/radiantearth/stac-site/contents/notebooks/src response). I believe these should work once the notebooks are incorporated into main, but we will need to check this to make sure.

Interesting. I'm not sure - we can merge and then see if it works. If we have a decent dev ops person then maybe they can try to get it working on branches...

> I put the example-catalog in the _site/public directory since that is where I was able to store and access embedded images, but I am not sure this is how we want to display this notebook to the user. In the development of these notebooks, the file was stored in the same directory as the Jupyter Notebooks, but with the html rendering of the notebooks, that file format does not work. I am open to different storage opens for the example-catalog (Used in the first Python tutorial).

I have no opinions here. Go with whatever makes sense to you.

Also I love that you're using the Divio system! I've long wanted to adopt that - it makes good sense to me. Would be great to have STAC be a great example of a fully fleshed version of that.

**Comment by PowerChell** [comment]
@cholmes the tutorials are updated and ready for your re-review. This round of updates:
- Incorporates all of your comments from the last round of reviews (QGIS tutorial focus). 
     - I ended up reformatting a lot of the second QGIS tutorial. 
- Expanded the page display width to fill more of the whitespace for all the tutorials. 
     - I've viewed the notebooks on a few different displays, but let me know if it's not looking right on yours. 

One issue that persist: I am having trouble getting the QGIS Advanced filter to work correctly. In the tutorial example, I suggest a query that should display only results for <10% cloud-covered images. Yet when I enter this query into the advanced filter, the plugin results in the following error: 

`Problem in fetching content for [https://planetarycomputer.microsoft.com/api/stac/v1.](https://planetarycomputer.microsoft.com/api/stac/v1.Error) Error details, None`

Not a very helpful error message.

I've attached a screenshot of the issue below. 

I want to have the tutorial include the use of the advanced filter, but I do not want to be suggesting something that I know is resulting in errors. The tutorial also currently reads a bit confusing since I mention the advanced filter but then am not actually applying it in the example. Would love to see if you are able to reproduce my error or know how to fix it. 

So, my remaining questions for you are:
1. What to do about this QGIS plugin issue described?
2. Are there any changes that need to be made to the updated intro to STAC spec tutorial or any of the Python tutorials before publishing to the STAC site? 

STAC QGIS plugin advanced filter error

**Comment by lossyrob** [comment]
Not sure what query this is doing to the Planetary Computer API, but this does succeed:

```python
import requests
url = "https://planetarycomputer.microsoft.com/api/stac/v1/search"
body = {
    "collections": ["landsat8", "sentinel-2-l2a"],
    "bbox": [-10.415,36.066,3.779,44.213],
    "limit": 200,
    "datetime": "2022-06-01T00:00:00Z/2022-06-30T00:00:00Z",
    "query": {
        "eo:cloud_cover": {
          "gte": 0,
          "lte": 10
        },
    }
}
resp = requests.post(url, json=body)
assert resp.status_code == 200
```
Using an arbitrary bbox and collections, as I don't see from the screenshot what those values were.

Perhaps an issue to file against the QGIS plugin repo?

**Comment by cholmes** [comment]
I'd say just cut the advanced filter for now, and get this merged, as it's lots of good work and would be good to actually 'ship' it. Then just make an issue for adding it in here, and then try to dig into reproduce it and get it fixed - figure out if it's the qgis plugin, planetary computer, etc. and file the bug there.

**Comment by PowerChell** [comment]
@cholmes Okay, I think it's finally ready!

Changes in this last round: 
- Removed the Advanced GIS filter portion of QGIS Tutorial 2. I will open up an issue here and with the QGIS plugin creators to address the issue described above.
- Ran Final grammar check and update on all 7 notebooks.
- Moved graphics and example-catalog from `_site/public` to the `assets` directory. Realized in my final review that the `assets` directory was definitely the place for these files. Answered my own question (# 3) from the original PR comment.

Should be good to ship!

**Pull request merged**
